### ISSUE TITLE
Flask errors?

### ISSUE THREAD

**Issue by StiffPP** [massiveschlong/onlyfans-content-downloader#3] opened 2022-05-14 23:28 UTC
![image](https://user-images.githubusercontent.com/91228046/168451213-faae848d-7552-4c89-8d93-cf2bdd61eeb8.png)

Also, i think it downloaded because it would say 100% on pics and vids on the console, but idk where it would have downloaded as i dont see any new folders made in my downloads or the folder where the the js and py files are. Any help?

**Comment by massiveschlong** [comment] 2022-05-15 07:52
You need to install Flask and Flask_CORS on your computer. The commands to install them are in the readme file.

Let me know if that solves your issue!

**Comment by StiffPP** [comment] 2022-05-15 19:41
> You need to install Flask and Flask_CORS on your computer. The commands to install them are in the readme file.
> 
> Let me know if that solves your issue!

So installed them, and now it says there are no issues in the problem tab when I run the .py thru the terminal. But, when I try and download someone's OF, it does the same thing. It "downloads" to 100% on pictures and videos, but nothing happens. There are no folders made in my downloads or the folder that contains the .py, and nothing changes after the "download".

Do you have a discord I can contact you on to show you?

**Comment by massiveschlong** [comment] 2022-05-15 21:00
Did you run the Python file as instructed in the readme screenshots?
You can drop your Discord here. I will contact you asap or you can write it here.

**Comment by StiffPP** [comment] 2022-05-15 22:17
Diddler From Da 9#3151

**Comment by massiveschlong** [comment] 2022-05-15 22:22
Hi, that's not a proper Discord username.
E.g.: username#9928

I cannot send you a DM at "Diddler From Da 9#3151"

**Comment by StiffPP** [comment] 2022-05-15 22:26
![image](https://user-images.githubusercontent.com/91228046/168496505-ae893437-052b-4a7e-a065-9366e2b414f0.png)
idk what to tell u bro

**Comment by massiveschlong** [comment] 2022-05-16 01:00
Since the issue is fixed. I will close this ticket.

**Closed by massiveschlong** 2022-05-16 01:00 UTC
